/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const ArticleId = IDL.Nat;
export const Article = IDL.Record({
  'id' : ArticleId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'slug' : IDL.Text,
  'publishedAt' : IDL.Int,
  'summary' : IDL.Text,
  'category' : IDL.Text,
  'readTimeMinutes' : IDL.Nat,
});
export const MessageId = IDL.Nat;
export const MessageStatus = IDL.Variant({
  'new' : IDL.Null,
  'read' : IDL.Null,
  'archived' : IDL.Null,
});
export const MessageType = IDL.Variant({
  'contact' : IDL.Null,
  'b2bConsultancy' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : MessageId,
  'status' : MessageStatus,
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'messageType' : MessageType,
  'company' : IDL.Opt(IDL.Text),
});
export const ProductId = IDL.Nat;
export const ProductCategory = IDL.Variant({
  'ebook' : IDL.Null,
  'firmware' : IDL.Null,
  'guide' : IDL.Null,
  'gerber' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'title' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'category' : ProductCategory,
  'image' : IDL.Text,
  'price' : IDL.Nat,
});
export const Specification = IDL.Record({
  'value' : IDL.Text,
  'caption' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'specifications' : IDL.Vec(Specification),
  'title' : IDL.Text,
  'slug' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'summary' : IDL.Text,
  'category' : IDL.Text,
  'images' : IDL.Vec(IDL.Text),
});
export const ArticleSummary = IDL.Record({
  'id' : ArticleId,
  'title' : IDL.Text,
  'slug' : IDL.Text,
  'publishedAt' : IDL.Int,
  'summary' : IDL.Text,
  'category' : IDL.Text,
  'readTimeMinutes' : IDL.Nat,
});
export const MessageSummary = IDL.Record({
  'id' : MessageId,
  'status' : MessageStatus,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'messageType' : MessageType,
  'company' : IDL.Opt(IDL.Text),
});
export const ProductSummary = IDL.Record({
  'id' : ProductId,
  'title' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'category' : ProductCategory,
  'image' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getArticle' : IDL.Func([ArticleId], [IDL.Opt(Article)], ['query']),
  'getArticleBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Article)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessage' : IDL.Func([MessageId], [IDL.Opt(Message)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProjectBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listArticles' : IDL.Func([], [IDL.Vec(ArticleSummary)], ['query']),
  'listMessages' : IDL.Func([], [IDL.Vec(MessageSummary)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(ProductSummary)], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'submitMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Text, MessageType],
      [MessageId],
      [],
    ),
  'updateMessageStatus' : IDL.Func(
      [MessageId, MessageStatus],
      [IDL.Opt(Message)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const ArticleId = IDL.Nat;
  const Article = IDL.Record({
    'id' : ArticleId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'slug' : IDL.Text,
    'publishedAt' : IDL.Int,
    'summary' : IDL.Text,
    'category' : IDL.Text,
    'readTimeMinutes' : IDL.Nat,
  });
  const MessageId = IDL.Nat;
  const MessageStatus = IDL.Variant({
    'new' : IDL.Null,
    'read' : IDL.Null,
    'archived' : IDL.Null,
  });
  const MessageType = IDL.Variant({
    'contact' : IDL.Null,
    'b2bConsultancy' : IDL.Null,
  });
  const Message = IDL.Record({
    'id' : MessageId,
    'status' : MessageStatus,
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'messageType' : MessageType,
    'company' : IDL.Opt(IDL.Text),
  });
  const ProductId = IDL.Nat;
  const ProductCategory = IDL.Variant({
    'ebook' : IDL.Null,
    'firmware' : IDL.Null,
    'guide' : IDL.Null,
    'gerber' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'title' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'category' : ProductCategory,
    'image' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Specification = IDL.Record({
    'value' : IDL.Text,
    'caption' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'specifications' : IDL.Vec(Specification),
    'title' : IDL.Text,
    'slug' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'summary' : IDL.Text,
    'category' : IDL.Text,
    'images' : IDL.Vec(IDL.Text),
  });
  const ArticleSummary = IDL.Record({
    'id' : ArticleId,
    'title' : IDL.Text,
    'slug' : IDL.Text,
    'publishedAt' : IDL.Int,
    'summary' : IDL.Text,
    'category' : IDL.Text,
    'readTimeMinutes' : IDL.Nat,
  });
  const MessageSummary = IDL.Record({
    'id' : MessageId,
    'status' : MessageStatus,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'messageType' : MessageType,
    'company' : IDL.Opt(IDL.Text),
  });
  const ProductSummary = IDL.Record({
    'id' : ProductId,
    'title' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'category' : ProductCategory,
    'image' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getArticle' : IDL.Func([ArticleId], [IDL.Opt(Article)], ['query']),
    'getArticleBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Article)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessage' : IDL.Func([MessageId], [IDL.Opt(Message)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProjectBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listArticles' : IDL.Func([], [IDL.Vec(ArticleSummary)], ['query']),
    'listMessages' : IDL.Func([], [IDL.Vec(MessageSummary)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(ProductSummary)], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'submitMessage' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          MessageType,
        ],
        [MessageId],
        [],
      ),
    'updateMessageStatus' : IDL.Func(
        [MessageId, MessageStatus],
        [IDL.Opt(Message)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };