/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : ArticleId,
  'title' : string,
  'content' : string,
  'slug' : string,
  'publishedAt' : bigint,
  'summary' : string,
  'category' : string,
  'readTimeMinutes' : bigint,
}
export type ArticleId = bigint;
export interface ArticleSummary {
  'id' : ArticleId,
  'title' : string,
  'slug' : string,
  'publishedAt' : bigint,
  'summary' : string,
  'category' : string,
  'readTimeMinutes' : bigint,
}
export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Message {
  'id' : MessageId,
  'status' : MessageStatus,
  'subject' : string,
  'body' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'messageType' : MessageType,
  'company' : [] | [string],
}
export type MessageId = bigint;
export type MessageStatus = { 'new' : null } |
  { 'read' : null } |
  { 'archived' : null };
export interface MessageSummary {
  'id' : MessageId,
  'status' : MessageStatus,
  'subject' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'messageType' : MessageType,
  'company' : [] | [string],
}
export type MessageType = { 'contact' : null } |
  { 'b2bConsultancy' : null };
export interface Product {
  'id' : ProductId,
  'title' : string,
  'slug' : string,
  'description' : string,
  'category' : ProductCategory,
  'image' : string,
  'price' : bigint,
}
export type ProductCategory = { 'ebook' : null } |
  { 'firmware' : null } |
  { 'guide' : null } |
  { 'gerber' : null };
export type ProductId = bigint;
export interface ProductSummary {
  'id' : ProductId,
  'title' : string,
  'slug' : string,
  'description' : string,
  'category' : ProductCategory,
  'image' : string,
  'price' : bigint,
}
export interface Project {
  'id' : bigint,
  'specifications' : Array<Specification>,
  'title' : string,
  'slug' : string,
  'year' : bigint,
  'description' : string,
  'summary' : string,
  'category' : string,
  'images' : Array<string>,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface Specification { 'value' : string, 'caption' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getArticle' : ActorMethod<[ArticleId], [] | [Article]>,
  'getArticleBySlug' : ActorMethod<[string], [] | [Article]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessage' : ActorMethod<[MessageId], [] | [Message]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getProductBySlug' : ActorMethod<[string], [] | [Product]>,
  'getProjectBySlug' : ActorMethod<[string], [] | [Project]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listArticles' : ActorMethod<[], Array<ArticleSummary>>,
  'listMessages' : ActorMethod<[], Array<MessageSummary>>,
  'listProducts' : ActorMethod<[], Array<ProductSummary>>,
  'listProjects' : ActorMethod<[], Array<Project>>,
  'schema' : ActorMethod<[], string>,
  'submitMessage' : ActorMethod<
    [string, string, [] | [string], string, string, MessageType],
    MessageId
  >,
  'updateMessageStatus' : ActorMethod<
    [MessageId, MessageStatus],
    [] | [Message]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];